---
title: "GENE315 - software installation"
author: "Mik Black"
date: "29 March 2021"
output: 
  html_document: default
  github_document: default
---

<!-- Run line below in R to render multiple documents: -->
<!-- rmarkdown::render(here::here("bioc461-setup.Rmd"), output_format='all') -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- NB: in 2021, I sent the below in a course announcement, rather than sending around a PDF -->

In this GENE315 lab module we will be using the R statistical software running in the RStudio 
application to perform data visualisation and analysis. You can use either your own computer for the lab, or you can use the computers in the CAL lab.

If you are using your own computer for this lab, you will need to have R and RStudio installed.  Install or update R **before** you install or update RStudio.

To install the latest version of R, visit the following website, and download the version for your operating system:

`http://cran.stat.auckland.ac.nz`

If you are running a version of R earlier than 4.0, that is probably okay, but just be aware that older versions of R do sometimes cause problems.

To install RStudio, visit the following website

`https://rstudio.com/products/rstudio/download`

and download the free version of "RStudio Desktop" for your operating system.

If you already have RStudio installed, you can upgrade to the latest version by choosing "Check for Updates" from the RStudio "Help" menu. 

**NB: you will be doing your analysis in RStudio, so don't worry about using the R application (it needs to be installed, but we don't have to open it) - just open RStudio and use that for all of your work.**

